// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZg-Cs4JR7H3F_Iv3Cf0R5Nv_5yLgB9o',
    appId: '1:1064536965925:web:dd31ada9189e10415fd0cc',
    messagingSenderId: '1064536965925',
    projectId: 'chatapp-10f06',
    authDomain: 'chatapp-10f06.firebaseapp.com',
    storageBucket: 'chatapp-10f06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBDqOWTOn1DkAg33gcMowItPaIz95tiM',
    appId: '1:1064536965925:android:632692bd9404e2725fd0cc',
    messagingSenderId: '1064536965925',
    projectId: 'chatapp-10f06',
    storageBucket: 'chatapp-10f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1jqvadlIfTg_yElsgMPfCvEAfx67L9k',
    appId: '1:1064536965925:ios:71470cbe08b6764e5fd0cc',
    messagingSenderId: '1064536965925',
    projectId: 'chatapp-10f06',
    storageBucket: 'chatapp-10f06.appspot.com',
    iosClientId: '1064536965925-i2fm9vdv5fk3pupvan24n2k59du81hpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj1jqvadlIfTg_yElsgMPfCvEAfx67L9k',
    appId: '1:1064536965925:ios:bb507079bd2662f45fd0cc',
    messagingSenderId: '1064536965925',
    projectId: 'chatapp-10f06',
    storageBucket: 'chatapp-10f06.appspot.com',
    iosClientId: '1064536965925-4oasainscgdi6cljm5en8edcfa7o9p0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessenger.RunnerTests',
  );
}
